instance_class: F2
runtime: python39
entrypoint: gunicorn -b :$PORT --timeout 120 app:app

automatic_scaling:
  target_cpu_utilization: .65
  min_instances: 1
  max_instances: 10

network: {}
resources: {}